version: "3"

# lists all the services by name
services:
  app:
    user: $UID:$GID
    build:
      context: .
    ports:
    - "8000:8000"
    volumes:
    - ./app:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
